### ISSUE TITLE
Davinci Resolve 18.6 Installed Using DavinciB

### ISSUE THREAD

**Issue by JumperTheHero** [zelikos/davincibox#82] opened 2024-06-11 00:18 UTC
Hello! I am using Garuda Linux (an arch distro). I got Davinci running using Davincibox, so thank you for this project! I personally am unsure on what could be causing this error. I see someone similar ones online, but that is to switch it to cuda. In this case, that seems likely impossible so I am unsure on what to do. Here is a screenshot of the error message and my GPU settings.

Error message when importing a video (Davinci Resolve 18.6.6): 

![Screenshot_20240610_191531](https://github.com/zelikos/davincibox/assets/109250665/82580e8c-89f8-46cf-911e-7a0d49800c19)

GPU Configuration in Davinci Resolve 18.6.6

![Screenshot_20240610_191751](https://github.com/zelikos/davincibox/assets/109250665/189dcf00-8191-44c6-803f-dd1c4817f6da)

Any idea on how to resolve this? Thanks!

**Comment by zelikos** [comment] 2024-06-11 00:21
Known issue; Resolve isn't currently working on AMD cards due to issues with both ROCm and rusticl.

Closing as duplicate of #74

**Closed by zelikos** 2024-06-11 00:21 UTC
