### ISSUE TITLE
Can't initialize OpenGL

### ISSUE THREAD

**Issue by mtwb47** [zelikos/davincibox#114] opened 2024-08-15 00:29 UTC
**Describe the bug**

When I run the setup script, I get a slew of  `Permission denied ` errors. I have attached the output where the errors occurred
[error.txt](https://github.com/user-attachments/files/16619950/error.txt)
.

**Installation method used**

- [ x ] `setup.sh`
- Manual
  - [ ] Distrobox
  - [ ] Toolbox

**To Reproduce**

1. run setup script per instructions
2. see errors 
3. Resolve does install, but will not run. It says that it cannot find openGL.

**Expected behavior**

Successful installation.

**Screenshots**

**System information (please complete the following)**

 - Distro: openSUSE Tumbleweed
 - Desktop Environment: KDE
 - GPU: RTX4070 TI Super

**Additional context**
I believe that outside of the permission denied issue I'm also having the same issue as  #83 but the steps taken there do not work for me.

![Screenshot_20240814_202714](https://github.com/user-attachments/assets/c8742019-d5b7-4f6a-946d-7d3f6ae014b2)

**Comment by zelikos** [comment] 2024-08-15 00:44
Yeah, those `permission denied` errors happen even for successful installations; those shouldn't be the cause of this issue.

Just to be sure: do you have `nvidia-container-toolkit` and `lshw` installed? The latter is needed if you use `setup.sh`, but not for manual setup; the former is a hard requirement for Nvidia GPUs.

**Comment by mtwb47** [comment] 2024-08-15 01:33
I do have both

IDK how much help I will be on testing this anymore, as I've (through blood sweat and tears) installed Resolve natively on openSUSE now.

**Comment by DaoistNeko** [comment] 2024-09-08 08:22
I'm having a vary similar issue, and I also have similar hardware and OS. Here are my full details. 

**Installation Method Used**

Manual: Distrobox

**To Reproduce**

Steps to reproduce the behavior:

1) Follow the manual installation per instructions
2) Resolve does install, but will not run. It says that it cannot find openGL. 
3) If you enter resolve using the integrated GPU, it will not detect the discrete nvidia GPU. It will then begin to default to the integrated GPU. 

**Expected Behavior**

Nvidia GPU detection and usage. 

**System information**

Distro: openSUSE Tumbleweed
Desktop Environment: KDE Plasma (x11)
GPU: RTX4070 TI Super (550.100)
GPU2: AMD Radeon Graphics (integrated)

**Additional Context and Debugging Attempts**

   I have NVIDIA Container Toolkit installed.

   I have lshw, but the install script can't detect the GPU anyway, so I decided to do it the manual way. 

  I managed to open it with an integrated GPU and found that it couldn't even detect the Nvidia GPU. Though this resulted in my inability to reproduce the "resolve could not initialize opengl: please ensure the latest..." error because it defaults to the integrated now. Deleting the config files in ``/home/USERNAME/.local/share/DaVinciResolve/configs/`` and the ones in the Resolve settings menu did not fix this. 
   I should also mention that manually switching to cuda processing mode in davinci is not an option. 

  I've generated a CDI file with ``sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml``, but that did not seem to have an effect. 

  I've checked that the GPU is available in davincibox by using ``nvidia-ctk cdi list`` inside and out of the box and found that the output matched. 
  Double checked this by comparing the output of ``podman run --rm --device nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi -L`` and ``nvidia-smi -L``
Output:

     nvidia.com/gpu=0
     nvidia.com/gpu=GPU-118331c9-7075-d4a2-c90e-3560f519c823
     nvidia.com/gpu=all

  I tried following all of the steps provided in #83 including:
1) Updating the distrobox with ``distrobox enter davincibox -- sudo dnf update``.
   It was up to date
2) Using the manual setup with custom flags from [distrobox's README](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#using-nvidia-container-toolkit).
   Fails because "nvidia/cuda" wasn't available. In the 3 options provided (opensuse, suse, and docker) they either did not have it, or denied me permission to use it.
3) Running Resolve with ``distrobox enter davincibox -- /usr/bin/run-davinci``.
   This does not change the behavior. 

**Logs**

[DaVinciLogs.zip](https://github.com/user-attachments/files/16921376/DaVinciLogs.zip) 
I've run it so many times that there are no more logs left from before it auto selected the integrated gpu. 

**Additionally**

Every time I reinstall davincibox, it takes more and more space while not resetting the settings. (I've used around 35gib, and not being able to reproduce the error exactly is caused by this as well). I'm uninstalling it with the script ``./setup.sh remove``, and then re-installing it manually.

**Comment by DaoistNeko** [comment] 2024-09-08 16:41
I managed to recreate the issue by simply unplugging the monitor. Here are the logs specific to the "...could not initialize OpenGL...". 

[ResolveDebug.txt](https://github.com/user-attachments/files/16922974/ResolveDebug.txt)

![image](https://github.com/user-attachments/assets/3ce97c8c-81dd-4c83-971b-ad692a4c14f1)

**Comment by DaoistNeko** [comment] 2024-09-12 05:24
**Semi-Solution**

This is a work in progress, and there are still errors, but I wanted to share my partial fix to help anyone who is also working on this. It's inspired off of the solution in #96. 

1) First we need to create an environment where we can edit the container.
``podman run ghcr.io/zelikos/davincibox dnf downgrade -y akmod-nvidia xorg-x11-drv-nvidia-cuda``
This command downgrades to the 550 driver version available in the fedora repos, which matches what opensuse has. If your driver isn't the 550 or 560 version, then you can build it from [the nvidia website](https://www.nvidia.com/en-us/drivers/unix/linux-amd64-display-archive/).

2) Now we need to find the container ID
``podman container list -a``

3) This will finalize the changes and create a commit ID
``podman commit CONTAINERID``

4) From here on you follow the manual steps in the README, but replace ``ghcr.io/zelikos/davincibox:latest`` with your commit ID. Like so:
``distrobox create -i COMMITID -n davincibox --nvidia``

**New Error**

Now you're able to successfully run glxinfo -B and nvidia-smi in the container and have it detect the GPU. Davinci resolve will also detect the GPU, but wont detect CUDA despite what the output of the two commands I mentioned earlier output. 

I tried running other programs like blender in the container, and they also cannot detect CUDA. I'll let you all know if I figure out the issue, and in the mean time, any help would be greatly appreciated. 

**Resolve Logs**

[ResolveDebug.txt](https://github.com/user-attachments/files/16973880/ResolveDebug.txt)
[resolve_graphics_log.txt](https://github.com/user-attachments/files/16973882/resolve_graphics_log.txt)

**Image**

![image](https://github.com/user-attachments/assets/d68ef204-7480-42af-a036-e586117cf933)

**Comment by DaoistNeko** [comment] 2024-09-13 23:58
**Solution**

Problem: 
The root cause of this issue is that davincibox comes with drivers pre-installed. This is unnecessary, so we will be removing them. Another part of the issue is that when opencl is installed, davinci resolve will default to it and not detect that cuda is also installed (my guess is that programs first look through distrobox before looking through the hose, and since davinci found something that satisfies it on the distrobox, it doesn't actually check the host). Once these are removed, assuming you use the ``--nvidia`` argument, it will simply use the drivers installed on the host. 
In theory, this solution should apply to #117 and #96 as well. 

**steps to fix**

1) First we need to edit the container provided zelikos and remove the files causing problems.
``podman run ghcr.io/zelikos/davincibox sudo dnf remove -y --noautoremove akmod-nvidia nvidia-modprobe nvidia-persistenced nvidia-setting xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia-cuda-libs xorg-x11-drv-nvidia-kmodsrc xorg-x11-drv-nvidia-libs xorg-x11-drv-nvidia-power intel-opencl rocm-opencl opencl-filesystem intel-opencl-clang``

2) Now we need to find the container ID for the next step. 
``podman container list -a``

3) This will finalize the changes and create a commit ID. Careful this is not the same as the container ID. 
``podman commit CONTAINERID``

4) From here on you follow the manual steps in the README, but replace ``ghcr.io/zelikos/davincibox:latest`` with your commit ID. Like so:
``distrobox create -i COMMITID -n davincibox --nvidia``
``/path/to/DaVinci_Resolve_version_Linux.run --appimage-extract`` (if you havn't already done so)
``distrobox enter davincibox -- setup-davinci squashfs-root/AppRun distrobox``

**You're done!**

Now when you enter davinci resolve, go to preferences, and click on "memory and gpu", you should see something kind of like this:

![image](https://github.com/user-attachments/assets/d366e78f-4dbf-4fdb-92cd-f199aa60622d)

**Note**

I'm so happy I finally figured out what was actually the problem. It's the first time I've ever touched containers so I ended up going down many rabbit holes that were unrelated, so this ended up taking a lot of time. Despite the hiccup, I have also come to appreciate the convenience that this script provides.

**Comment by zelikos** [comment] 2024-09-14 00:31
@DaoistNeko Thanks for taking the time to investigate this so thoroughly. I don't have an NVIDIA GPU so troubleshooting anything NVIDIA is basically impossible on my end.

My guess here is that, maybe when the switch from `nvidia-container-runtime` to `nvidia-container-toolkit` happened a while ago, it also resulted in the host drivers being able to be passed through to the container, which I don't believe was the case before. So if davincibox can work without including the NVIDIA drivers, and if doing so fixes a number of issues, that's great to know. This is a big change that would need wider testing, though.

As for the OpenCL drivers, we're already checking for the GPU driver being used, so updating the setup scripts to conditionally install them for Intel and AMD shouldn't be difficult. That, or providing a `davincibox-nvidia` variant in the future that omits them (or the inverse, `davincibox-opencl` that includes them).

cc @Zeglius since you do a lot to integrate davincibox in Bazzite and I don't want to break things there (again)

**Comment by DaoistNeko** [comment] 2024-09-14 01:36
No problem, I'm just happy to get DaVinci up and running. Since the fix is simple enough (no extra dependencies) and documented, you can take however long you need to implement it.

**Comment by Zeglius** [comment] 2024-09-14 17:19
Can confirm,DaoistNeko fix seems to work for me.

This is a screenshot made after manual installation with https://github.com/zelikos/davincibox/issues/114#issuecomment-2350719661 steps.
![image](https://github.com/user-attachments/assets/d5770fa2-c52b-4967-bd68-b8badabab132)


However using the normal installation procedure I get the same error https://github.com/zelikos/davincibox/issues/114#issue-2467049315

**Comment by Zeglius** [comment] 2024-09-14 17:33
Also seems removing dependencies after setting the container up (including running the `setup-davinci`) and afterwards restarting the container works as well.

**Comment by DaoistNeko** [comment] 2024-09-14 22:14
Yes, and I was able to remove all opencl packages while davincibox was running and have everything work fine without a restart. I just had trouble with making changes to the nvidia drivers, and when I made the guide I combined the steps for simplicity.

**Comment by zelikos** [comment] 2024-09-16 18:11
The NVIDIA driver issues should be fixed as of #121; if this issue persists after [upgrading](https://github.com/zelikos/davincibox?tab=readme-ov-file#upgrading), feel free to re-open.

**Closed by zelikos** 2024-09-16 18:11 UTC
Labels: help wanted, nvidia
